FIND_PATH(SSVSTART_INCLUDE_DIR
  NAMES SSVStart/SSVStart.hpp
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVStart/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVStart/"
  ${SSVSTART_ROOT}
  $ENV{SSVSTART_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVStart include at: ${SSVSTART_INCLUDE_DIR}.\n")

IF(SSVSTART_INCLUDE_DIR)
  SET(SSVSTART_FOUND TRUE)
ELSE(SSVSTART_INCLUDE_DIR)
  SET(SSVSTART_FOUND FALSE)
ENDIF(SSVSTART_INCLUDE_DIR)

IF(SSVSTART_FOUND)
  MESSAGE(STATUS "Found SSVStart in ${SSVSTART_INCLUDE_DIR}")
ELSE(SSVSTART_FOUND)
  IF(SSVSTART_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SSVStart library")
  ENDIF(SSVSTART_FIND_REQUIRED)
ENDIF(SSVSTART_FOUND)

MARK_AS_ADVANCED(
  SSVSTART_INCLUDE_DIR
)
